version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d/
    command: mongod --auth 

volumes:
  mongo-data:
