export const template = (
    body: string,
    bodyCss: string,
    mediaCss: string
  ): string => {
    return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <style>
      html {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue",
          sans-serif;
        font-size: 18px;
        font-weight: 400;
        line-height: 160%;
        padding: 0;
        margin: 0;
      }
      body {
        padding: 0;
        margin: 0;
      }
      p {
        padding: 0;
        margin: 0;
      }
      .root {
        width: 100%;
      }
      .body {
        max-width: 600px;
        margin: 0 auto;
        height: auto;
        background-color: white;
      }
      .header {
        width: 100%;
        height: auto;
        text-align: center;
      }
      .img-container {
        margin: auto;
        width: 100%;
        object-fit: cover;
        background-size:cover;
        background-position:center;
        background-repeat:no-repeat;	
      }
      .frame {
        width: 100%;
        height: auto;
        padding-bottom: 20px;
      }
  
      .logo {
        width: 60%;
        height: auto;
      }
      .main {
        margin-top: -70px;
        padding: 20px;
      }
      ${bodyCss}    
      .att {
        padding-left: 20px;
        margin-bottom: 45px;
      }
      .italic {
        font-style: italic;
      }
  
      .blue {
        color: #1e429f;
      }
  
      .end {
        text-align: justify;
        font-size: 15px;
        padding: 20px;
        background-color: #f3f4f6;
      }
  
      @media (max-width: 600px) {
        html {
          line-height: 100%;
        }
        .main {
          margin-top: -50px;
        }
        ${mediaCss}     
         .att {
          padding-top: 0px;
          margin-bottom: 30px;
        }
  
        .footer {
          font-size: 14px;
        }
  
        .end{
          font-size: 14px;
        }
      }
    </style>
    </head>
    <div class="body">
      <div class="header">
        <div class="img-container">
         <img class="frame" src="https://i.imgur.com/s1cKk8Z.png"/>
        </div>
        <div>
         <img class="logo" src="https://your-app-logo-link.com/logo.png"/>
        </div>
      </div>
      <div class="main">
      
      ${body}
      
      
      </div>
      <div class="footer">
          <div class="att">
            <p class="italic">Sincerely,</p>
            <p class="italic">The LandFinder Team</p>
          </div>
          <p class="end">
            This email has been automatically generated by our system. Please do not reply to this message.
          </p>
        </div>
    </div>
  </html>
  `;
  };
